version: "3.7"

services:

  # driver
  driver:
    build: ./driver
    container_name: driver
    depends_on:
      - namenode
      - datanode
      - hive-server
    # command: bash
    # tty: true

  # Hadoop, HDFS
  namenode:
    # image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    build: ./namenode
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name # keep HDFS contents between container restarts
      # set HOST_DATASET_PATH in the .env file before running; makes dataset available in namenode (at /_host_data) for adding to HDFS
      - ${HOST_DATASET_PATH}:/_host_data
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "15070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data # keep HDFS contents between container restarts
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "15010:50010"
      - "15075:50075"
    depends_on:
      - namenode
  
  hue:
    image: bde2020/hdfs-filebrowser
    container_name: hue
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - "8088:8088"
    depends_on:
      - namenode
  

  # Hive
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
      - namenode
      - datanode

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0

  # presto-coordinator:
  #   image: shawnzhu/prestodb:0.181
  #   ports:
  #     - "8080:8080"


  # Hbase (unused)
  # hbase:
  #   image: dajobe/hbase
  #   container_name: hbase
  #   ports:
  #     - "8085:8085"
  #     - "9090:9090"
  #     - "9095:9095"
  #     - "16010:16010"

  # hbase_import:
  #   build: ./hbase_import
  #   depends_on: 
  #     - hbase
  #   environment:
  #     - PYTHONUNBUFFERED=1 # default buffering causes massive delay on logs, docker attach hnags
    
  

volumes:
  namenode:
  datanode:

